---
on.push.branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish-storybook
        with.path: build
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
...
