---
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
     - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish-storybook
        with:
          path: storybook-static
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
...
